name = "AdaptiveSampling"
uuid = "7f6f9940-4a32-4051-b522-c9b67e93c232"
authors = ["nvale <nvale3@uwo.ca>, tbrysiewicz <taylorbrysiewicz@gmail.com>"]
version = "0.1.0"

[deps]
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DelaunayTriangulation = "1.6.4"
GLMakie = "0.13.6"
LinearAlgebra = "1.11.0"
Plots = "1.40.17"
